name: Build Kernel for GTA9 + KernelSU

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          bc bison flex libssl-dev make libc6-dev libncurses5-dev \
          gcc clang python3 \
          gcc-aarch64-linux-gnu

    - name: Checkout Kernel Source
      uses: actions/checkout@v4
      with:
        repository: sir-solderet/android_kernel_samsung_gta9
        path: kernel

    - name: Clone KernelSU and setup
      run: |
        cd kernel
        git clone --depth=1 https://github.com/tiann/KernelSU
        bash KernelSU/setup.sh

    - name: Set up environment variables
      run: |
        echo "CROSS_COMPILE=aarch64-linux-gnu-" >> $GITHUB_ENV
        echo "ARCH=arm64" >> $GITHUB_ENV
        echo "KERNEL_DEFCONFIG=gta9_defconfig" >> $GITHUB_ENV
        echo "OUT_DIR=out" >> $GITHUB_ENV

    - name: Disable ABI symbol list check
      run: |
        sed -i '/abi_symbollist.raw/,+1d' kernel/Makefile

    - name: Build Kernel
      run: |
        cd kernel
        mkdir -p $OUT_DIR
        make O=$OUT_DIR $KERNEL_DEFCONFIG
        make -j$(nproc) O=$OUT_DIR

    - name: Upload Kernel Image
      uses: actions/upload-artifact@v4
      with:
        name: kernel-image
        path: |
          kernel/out/arch/arm64/boot/Image*
