name: Build GTA9 Kernel

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential bc bison flex libssl-dev \
            libncurses5-dev libelf-dev gcc-aarch64-linux-gnu

      - name: Clone kernel source
        run: |
          mkdir -p kernel/samsung
          git clone https://github.com/sir-solderet/android_kernel_samsung_gta9.git kernel/samsung/gta9
      - name: Build kernel
        run: |
          cd kernel/samsung/gta9
          mkdir -p out
          export ARCH=arm64
          export CROSS_COMPILE=$CROSS_COMPILE
          export KBUILD_BUILD_USER=github
          export KBUILD_BUILD_HOST=actions
          make O=out gta9_defconfig
          make O=out abi_symbollist=$GITHUB_WORKSPACE/abi_symbollist.raw -j$(nproc)
          make O=out ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu-
          make -j$(nproc) O=out ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu-

      - name: Upload kernel Image.gz
        uses: actions/upload-artifact@v4
        with:
          name: kernel-image
          path: kernel/out/arch/arm64/boot/Image.gz
