name: Build GTA9 Kernel

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential bc bison flex libssl-dev \
            libncurses5-dev libelf-dev gcc-aarch64-linux-gnu

      - name: Clone kernel source
        run: |
          mkdir -p kernel/samsung
          git clone https://github.com/sir-solderet/android_kernel_samsung_gta9.git kernel/samsung/gta9
          
      - name: Build kernel
        run: |
          cd kernel/samsung/gta9
          mkdir -p out
          export ARCH=arm64
          export CROSS_COMPILE=aarch64-linux-gnu-
          export CROSS_COMPILE64=aarch64-linux-gnu-
          export KBUILD_BUILD_USER=github
          export KBUILD_BUILD_HOST=actions
          export CONFIG_WERROR=n
          make O=out gta9_defconfig
          make -j$(nproc) O=out ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- KCFLAGS="-Wno-error=format" 2>&1 | tee out/build.log

      - name: Show full build log on failure
        if: failure()
        run: |
          echo "===== Kernel Build Failed. Showing last 200 lines of log ====="
          tail -n 200 kernel/samsung/gta9/out/build.log || true

      - name: Upload full build log (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: kernel-build-log
          path: kernel/samsung/gta9/out/build.log

      - name: Verify kernel image exists
        run: |
          IMAGE=kernel/samsung/gta9/out/arch/arm64/boot/Image.gz-dtb
          if [ ! -f "$IMAGE" ]; then
            echo "❌ Kernel image not found: $IMAGE"
            exit 1
          else
            echo "✅ Kernel image built: $IMAGE"
          fi

      - name: Upload kernel Image.gz
        uses: actions/upload-artifact@v4
        with:
          name: kernel-image
          path: kernel/out/arch/arm64/boot/Image.gz
